### ISSUE TITLE
Create environment.yml files on the fly in GitHub Actions workflows

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#2814]
Currently, we have six workflows (e.g., `ci_dos.yml`) that use the `mamba-org/setup-micromamba` action to create a conda environment. Each workflow has different purposes so they install different packages and sometimes different pinned versions. It's impossible to create a single `environment.yml` that can be used in different workflows. Thus, we have to pass a list of packages to the `creat-args` option of the `mamba-org/setup-micromamba` action. E.g., 
https://github.com/GenericMappingTools/pygmt/blob/b873c366ce142859c74116d7f05273773cd2fe7c/.github/workflows/ci_tests.yaml#L106-L122

It means we have to update several workflow files if we want to pin a package, add a new required/optional package, or add a new dev package, which is tedious.

To avoid maintaining the package list in so many places, we can write a bash script that can create `environment.yml` files on the fly for different purposes. Then we can use the generated `environment.yml` file in the `mamba-org/setup-micromamba` action.

Here is an initial/incompleted version of the script:
```bash
required="numpy pandas xarray netCDF4 packaging"

cat << EOF
name: pygmt
channels:
  - conda-forge
  - nodefaults
dependencies:
EOF

for package in $required; do
    if [[ -v NUMPY_VERSION && "$package" == "numpy" ]]; then
        echo "  - $package=${NUMPY_VERSION}"
    else
        echo "  - $package"
    fi
done
```
By default, it produces:
```yaml
name: pygmt
channels:
  - conda-forge
  - nodefaults
dependencies:
  - numpy
  - pandas
  - xarray
  - netCDF4
  - packaging
```
If we define an environment variable `export NUMPY_VERSION=1.26`, it produces:
```yaml
name: pygmt
channels:
  - conda-forge
  - nodefaults
dependencies:
  - numpy=1.26
  - pandas
  - xarray
  - netCDF4
  - packaging
```

- **Pros**: fewer files to maintain when we add/remove/pin packages
- **Cons**: need to write and maintain a bash script in the repository, which may be not as simple as I thought

Comments?
