### ISSUE TITLE
Slash command "/format" doesn't work for external contributors

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#767]
**Description of the problem**

https://github.com/GenericMappingTools/pygmt/pull/766#issuecomment-751356843 doesn't trigger the format command. Instead, the [slash dispatch action](https://github.com/GenericMappingTools/pygmt/actions/runs/445575126) reports:
```
Run peter-evans/slash-command-dispatch@v2
  with:
    token: ***
    commands: format
  
    issue-type: pull-request
    reaction-token: ***
    reactions: true
    permission: write
    allow-edits: false
    repository: GenericMappingTools/pygmt
    event-type-suffix: -command
    dispatch-type: repository
Using configuration from yaml inputs.
Command 'format' is not configured for the user's permission level 'none'.
```

It seems something wrong with the permission setting.
